apiVersion: v1
kind: PersistentVolume
metadata:
  name: safevault-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/safevault-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: safevault-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual